### ISSUE TITLE
Setup failing so far, not getting entities in MQTT.

### ISSUE THREAD

**Issue by Wolfang42** [BigThunderSR/adt-pulse-mqtt#246]
Ok, thanks @BigThunderSR for directing me here.

I have followed the instructions to the letter (as best I can tell)

I am getting this error:

```
This entity ('alarm_control_panel.adt_pulse') does not have a unique ID, therefore its settings cannot be managed from the UI. 
See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.
```
I have configured the addon:

```
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
pulse_login:
  username: **redacted**
  password: **redacted**
  fingerprint: >-**redacted**
mqtt_host: core-mosquitto
mqtt_url: ""
mqtt_connect_options:
  username: homeassistant
  password: **redacted**
alarm_state_topic: home/alarm/state
alarm_command_topic: home/alarm/cmd
zone_state_topic: adt/zone
smartthings_topic: smartthings
smartthings: false
```

Perhaps the MQTT password is wrong but I cut/pasted it from the MQTT config?

Here is a log snippet:

```
3/2/2025, 11:25:15 PM Pulse.Sync: Syncing 171516-0-0
3/2/2025, 11:25:15 PM Pulse: updateAll
3/2/2025, 11:25:15 PM Pulse.getAlarmStatus: Getting Alarm Statuses
3/2/2025, 11:25:16 PM Pulse.getDeviceStatus: Getting Device Statuses
3/2/2025, 11:25:16 PM Pulse.getZoneStatus(via Orb): Getting Zone Statuses
3/2/2025, 11:25:16 PM Pulse.getDeviceStatus No other devices found
3/2/2025, 11:25:17 PMADT Pulse: Get zone status (via orb) success.
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: 1st Bedroom Central Tags: sensor State devStatOK
3/2/2025, 11:25:17 PM: Pushing device state: devStatOK to topic adt/zone/1st Bedroom Central/state
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: 1st Bedroom Left Tags: sensor State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: 1st Bedroom Right Tags: sensor State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: 1st Floor Motion Tags: sensor,motion State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: 2nd Bedroom Central Tags: sensor State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: 2nd Bedroom Left Tags: sensor State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: 2nd Bedroom Right Tags: sensor State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: 2nd Floor Gas Tags: sensor,co State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: 2nd Floor Motion Tags: sensor,motion State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: 2nd Floor Smoke Tags: sensor,fire State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: 2nd Floor Window Tags: sensor,doorWindow State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: Family Glass Detector Tags: sensor,glass State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: Family Room Door Tags: sensor,doorWindow State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: Front Door Tags: sensor,doorWindow State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: Garage Door Tags: sensor,doorWindow State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: Garage Laundry Door Tags: sensor,doorWindow State devStatOK
3/2/2025, 11:25:17 PM: Pushing device state: devStatOK to topic adt/zone/Garage Laundry Door/state
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: Living Room Door Tags: sensor,doorWindow State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: Master Bedroom Door Tags: sensor,doorWindow State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: Rear Glass Detector Tags: sensor,glass State devStatOK
3/2/2025, 11:25:17 PM Sensor: sensor-0 Name: Rear Motion Detector Tags: sensor,motion State devStatOK
3/2/2025, 11:25:17 PM Pulse setAlarmState New SAT ::487c9ebd-ad5c-4b22-897f-9faf2e2807b6::
```
